"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tBnplM1FE9N
 */

import Link from "next/link";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import dynamic from "next/dynamic";
import React, { lazy, Suspense } from "react";
const Navbar = dynamic(() => import("@/components/component/navbar"));
import Image from "next/image";

import HeroImage from "@/assets/images/hero2.png";

import bisleri from "@/assets/images/hero.png";
import aquafina from "@/assets/images/aquafina.png";
import sprite from "@/assets/images/sprite.png";
import pepsi from "@/assets/images/pepsi.png";
import schwepps from "@/assets/images/schwepps.png";
import logo from "@/assets/images/cocacola.png";
import logo2 from "@/assets/images/logo3.png";

export function landingPage() {
  var settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 4,
    initialSlide: 0,
    // waitForAnimate: false,
    // fade: true,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
          initialSlide: 2,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };

  const products = [
    {
      name: "Aquafina",
      image: aquafina,
    },
    {
      name: "Sprite",
      image: sprite,
    },
    {
      name: "Schwepps Tonic Water",
      image: schwepps,
    },

    {
      name: "Pepsi",
      image: pepsi,
    },
  ];
  return (
    <div key="1" className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <Navbar />
      </header>
      <main className="flex-1">
        <section
          className="w-full pt-12 md:pt-24 lg:pt-32 border-y bg-[#083d04] text-white dark:bg-[#083d04] dark:text-white"
          id="home"
        >
          <div className="container space-y-10 px-4 sm:px-6 md:space-y-16 md:px-10 ">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  The Perfect Bottle for Every Lifestyle
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Beautifully designed, durable, and sustainable. Our bottles
                  are designed to keep you hydrated in style.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 sm:grid-cols-2 md:gap-12 lg:max-w-none lg:grid-cols-3">
              <div className="flex flex-col items-start space-y-2">
                <h3 className="text-xl font-bold">Active Lifestyle</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Perfect for those who are always on the go. Our insulated
                  bottles keep your drinks cold for 24 hours or hot for 12
                  hours.
                </p>
              </div>
              <Image
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-contain object-center sm:w-full"
                height="310"
                src={HeroImage}
                width="550"
              />
              <div className="flex flex-col items-start space-y-2">
                <h3 className="text-xl font-bold">Fashionable Designs</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Express your style with our collection of beautifully designed
                  bottles. From sleek and modern to bold and vibrant, we have
                  something for everyone.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-2">
                <h3 className="text-xl font-bold">Fashionable Designs</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Express your style with our collection of beautifully designed
                  bottles. From sleek and modern to bold and vibrant, we have
                  something for everyone.
                </p>
              </div>
              <Image
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-contain object-center sm:w-full"
                height="310"
                src={HeroImage}
                width="550"
              />
              <div className="flex flex-col items-start space-y-2">
                <h3 className="text-xl font-bold">Active Lifestyle</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Perfect for those who are always on the go. Our insulated
                  bottles keep your drinks cold for 24 hours or hot for 12
                  hours.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-red-100"
          id="products"
        >
          <div className="container grid items-center gap-10 px-4 text-center md:px-6 lg:gap-16">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Shop Our Collection
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Choose from a variety of colors and designs. Our bottles are not
                only functional but also a fashion statement.
              </p>
            </div>
            <div className="slider-container mx-auto max-w-5xl w-full">
              <Slider {...settings}>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 1"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={aquafina}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium mr-11">Sporty Blue</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 2"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={sprite}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium">Eco-Friendly Green</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={schwepps}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium">Classic White</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={pepsi}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium">Classic White</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={pepsi}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium">Classic White</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={pepsi}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium">Classic White</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-right"
                    height="400"
                    src={pepsi}
                    width="400"
                  />

                  {/* <h3 className="text-sm font-medium mr-5">Classic White</h3> */}
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Image
                    alt="Bottle 3"
                    className="aspect-square overflow-hidden rounded-lg object-contain object-center"
                    height="400"
                    src={pepsi}
                    width="400"
                  />
                  {/* <h3 className="text-sm font-medium mr-7">Classic White</h3> */}
                </div>
                {/* </div> */}
              </Slider>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#083d04] text-white dark:bg-gray-800">
          <div className="container grid items-center gap-10 px-4 text-center md:px-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Limited Edition
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Check out our exclusive limited edition water bottles. Grab them
                before theyre gone!
              </p>
            </div>
            <div className="mx-auto grid max-w-4xl items-start gap-4 sm:gap-6 lg:grid-cols-3 lg:gap-8">
              <div className="relative group">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View</span>
                </Link>
                <img
                  alt="Sparkling Gold"
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                  height={200}
                  src="/placeholder.svg"
                  width={200}
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    Sparkling Gold
                  </h3>
                  <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                    Price: $29.99
                  </small>
                </div>
              </div>
              <div className="relative group">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View</span>
                </Link>
                <img
                  alt="Midnight Black"
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                  height={200}
                  src="/placeholder.svg"
                  width={200}
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    Midnight Black
                  </h3>
                  <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                    Price: $34.99
                  </small>
                </div>
              </div>
              <div className="relative group">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View</span>
                </Link>
                <img
                  alt="Rose Quartz"
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                  height={200}
                  src="/placeholder.svg"
                  width={200}
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">Rose Quartz</h3>
                  <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                    Price: $39.99
                  </small>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-white dark:bg-gray-800">
          <div className="mx-auto grid max-w-4xl items-start gap-4 sm:gap-6 lg:grid-cols-2 lg:gap-10">
            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Our Water
                </h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Learn about the quality and sustainability of our water
                  sources.
                </p>
                <img
                  alt="Water Source"
                  className="mx-auto aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height="250"
                  src="/placeholder.svg"
                  width="500"
                />
              </div>
            </div>

            <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Our Story
                </h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Discover the journey and inspiration behind our brand.
                </p>
                <img
                  alt="Brand Inspiration"
                  className="mx-auto aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height="250"
                  src="/placeholder.svg"
                  width="500"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-10 px-4 text-center md:px-6 lg:gap-16">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Why Choose Us?
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Discover why our water bottles are the best choice for you.
                Quality, style, and sustainability combined in every bottle.
              </p>
            </div>
            <div className="mx-auto flex w-full items-center justify-center p-8 sm:p-12">
              <Image
                alt="Image"
                className="aspect-[3/2] overflow-hidden rounded-lg object-contain object-center"
                height="500"
                src={pepsi}
                width="750"
              />
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"
          id="about"
        >
          <div className="container grid items-center gap-10 px-4 text-center md:px-6">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                About Us
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We are passionate about providing high-quality, stylish, and
                eco-friendly water bottles to our customers. Our mission is to
                make hydration fun and convenient.
              </p>
            </div>
            <div className="mx-auto grid max-w-4xl items-start gap-4 sm:gap-6 lg:grid-cols-2 lg:gap-10">
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <Image
                  alt="Image"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height="250"
                  src={logo}
                  width="500"
                />
              </div>
              <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                <Image
                  alt="Image"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height="250"
                  src={logo2}
                  width="500"
                />
              </div>
            </div>
            <div className="flex-1 py-4">
              <h3 className="font-semibold tracking-tight">Sparkling Gold</h3>
              <small className="text-sm leading-none text-gray-500 dark:text-gray-400">
                Price: $29.99
              </small>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32" id="contact">
          <div className="container grid items-center gap-10 px-4 text-center md:px-6 lg:gap-16">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Contact Us
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Have a question? Want to place a bulk order? Reach out to us and
                we will get back to you as soon as possible.
              </p>
            </div>
            <div className="mx-auto max-w-[400px] space-y-4">
              <form className="space-y-4">
                <div className="grid sm:grid-cols-2 gap-4">
                  <Input placeholder="First Name" type="text" />
                  <Input placeholder="Last Name" type="text" />
                </div>
                <Input placeholder="Email" type="email" />
                <Input placeholder="Subject" type="text" />
                <Textarea
                  className="min-h-[150px]"
                  placeholder="Your Message"
                />
                <Button type="submit">Submit</Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Acme Inc. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
