import { Inter } from "next/font/google";
import "./globals.css";
// import the library
import { library } from "@fortawesome/fontawesome-svg-core";

// import your icons
import { fab } from "@fortawesome/free-brands-svg-icons";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
{
  /* The following line can be included in your src/index.js or App.js file */
}
import "bootstrap/dist/css/bootstrap.min.css";
import "../assets/css/style.css";
import "../assets/css/responsive.css";
import "../assets/css/owl.css";
import "../assets/css/animate.css";
import "../assets/css/color.css";
import "../assets/css/flaticon.css";
import "../assets/css/font-awesome-all.css";
import "../assets/css/jquery.fancybox.min.css";
import "../assets/css/jquery-ui.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// Add your icons
library.add(fab, fas, far);
